// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalDbModel.DbModels;

[Table("BasePrice", Schema = "rental")]
[Index("IdBasePrice", Name = "idBasePrice_UNIQUE", IsUnique = true)]
public partial class BasePrice
{
    [Key]
    [Column("idBasePrice")]
    public int IdBasePrice { get; set; }

    [Required]
    [StringLength(100)]
    public string PriceName { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Amount { get; set; }
}