// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CarRentalDbModel.DbModels;

public partial class CarRentalContext : DbContext
{
    public CarRentalContext(DbContextOptions<CarRentalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BasePrice> BasePrices { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Rental> Rentals { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<VehicleType> VehicleTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BasePrice>(entity =>
        {
            entity.HasKey(e => e.IdBasePrice).HasName("PK__BasePric__05A7792CB3E8FD47");
        });

        modelBuilder.Entity<Rental>(entity =>
        {
            entity.HasKey(e => e.IdRental).HasName("PK__Rental__8E0AA7C8AB447680");

            entity.HasOne(d => d.FkCustomerNavigation).WithMany(p => p.Rentals)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("rental_customer");

            entity.HasOne(d => d.FkVehicleNavigation).WithMany(p => p.Rentals)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("rental_vehicle");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.IdVehicle).HasName("PK__Vehicle__B5E24754A4F88D74");

            entity.HasOne(d => d.FkVehicleTypeNavigation).WithMany(p => p.Vehicles).HasConstraintName("vehicle_vehicletype");
        });

        modelBuilder.Entity<VehicleType>(entity =>
        {
            entity.HasKey(e => e.IdVehicleType).HasName("PK__VehicleT__EDA0D143AA059AE8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}