// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalDbModel.DbModels;

[Table("Customer", Schema = "rental")]
[Index("IdCustomer", Name = "idCustomer_UNIQUE", IsUnique = true)]
public partial class Customer
{
    [Key]
    [Column("idCustomer")]
    public int IdCustomer { get; set; }

    [Required]
    [Column("SSN")]
    [StringLength(20)]
    public string Ssn { get; set; }

    [InverseProperty("FkCustomerNavigation")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}