// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalDbModel.DbModels;

[Table("Rental", Schema = "rental")]
[Index("BookingNumber", Name = "UQ__Rental__AAC320BF99EC189F", IsUnique = true)]
[Index("FkCustomer", Name = "rental_customer_idx")]
[Index("FkVehicle", Name = "rental_vehicle_idx")]
public partial class Rental
{
    [Key]
    [Column("idRental")]
    public int IdRental { get; set; }

    [Column("fkCustomer")]
    public int FkCustomer { get; set; }

    [Column("fkVehicle")]
    public int FkVehicle { get; set; }

    [Required]
    [StringLength(10)]
    public string BookingNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PickupDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReturnDateTime { get; set; }

    public int PickupMeeterKm { get; set; }

    public int? ReturnMeterKm { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal KmPrice { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal DayPrice { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? RentalPrice { get; set; }

    [ForeignKey("FkCustomer")]
    [InverseProperty("Rentals")]
    public virtual Customer FkCustomerNavigation { get; set; }

    [ForeignKey("FkVehicle")]
    [InverseProperty("Rentals")]
    public virtual Vehicle FkVehicleNavigation { get; set; }
}