// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalDbModel.DbModels;

[Table("VehicleType", Schema = "rental")]
[Index("IdVehicleType", Name = "idCarType_UNIQUE", IsUnique = true)]
public partial class VehicleType
{
    [Key]
    [Column("idVehicleType")]
    public int IdVehicleType { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal KmFactor { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal DayFactor { get; set; }

    [InverseProperty("FkVehicleTypeNavigation")]
    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}