// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRentalDbModel.DbModels;

[Table("Vehicle", Schema = "rental")]
[Index("RegistrationNumber", Name = "UQ__Vehicle__E8864602019C889B", IsUnique = true)]
public partial class Vehicle
{
    [Key]
    [Column("idVehicle")]
    public int IdVehicle { get; set; }

    [Column("fkVehicleType")]
    public int? FkVehicleType { get; set; }

    [StringLength(20)]
    public string RegistrationNumber { get; set; }

    [ForeignKey("FkVehicleType")]
    [InverseProperty("Vehicles")]
    public virtual VehicleType FkVehicleTypeNavigation { get; set; }

    [InverseProperty("FkVehicleNavigation")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}